### PR TITLE
Implement IdGenerator and changing add appt cmd

### LINKED ISSUE #127: Create Feature to check if Doctor/Patient exist when adding appointment.

### LINKED ISSUE #138: [PE-D] Error message for name in add patient command
For the name segment of the command, the error message is the same when I entered a number in the name and when I entered a special character. Consider splitting the type of error messages.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: froststein/ped#1

### LINKED ISSUE #139: [PE-D] Error message for needing a number for add patient command
The error message is not clear as to which field needs to be a number.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: froststein/ped#2

### LINKED ISSUE #141: [PE-D] View doctor alternative format does not work as expected
Unable to view doctor when using the format `view doctor /info [nric]`

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: bbawj/ped#1

### LINKED ISSUE #143: [PE-D] View patient alternative format does not work as expected
Unable to view patient when using the format view patient /info [nric]

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: bbawj/ped#2

### LINKED ISSUE #144: [PE-D] View patient command not working with NRIC argument
The view patient command does not work when NRIC is supplied as an argument.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: froststein/ped#5

### LINKED ISSUE #146: [PE-D] Typo for example usage in view patient
Typo error.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: bbawj/ped#3

### LINKED ISSUE #147: [PE-D] View command for patient user guide example
Wrong command example for view patient.
Should be `view patient /info S1234567A`

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: froststein/ped#6

### LINKED ISSUE #148: [PE-D] View medicine alternative format does not work as expected
Unable to view doctor when using the format `view medicine /info [name]`

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: bbawj/ped#4

### LINKED ISSUE #149: [PE-D] View Doctor command not working with NRIC argument
View doctor command has the same error as view patient, where the command does not work when NRIC argument is supplied.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: froststein/ped#7

### PR DESCRIPTION
**Pull request by tanweili**
Create IdGenerator class to create id in a specific way for adding appt.
Also, AppointmentList now takes in PatientList and DoctorList into its
constructor for referencing in order to simplify the add appt inputs
and check if the doctor and patient exists, and if an appt is already
schedule on the date given. Next step is to reference from patient
and doctor to appt as discussed.

### CODE REVIEW

**Comment by tanweili** [comment]
#144 fixing together with commit that fixes #143

**Comment by tanweili** [comment]
#146 fixing together with commit for #143

**Comment by tanweili** [comment]
#147 fixing together with commit that fixes #143

**Comment by tanweili** [comment]
#149 fixing together with #148

**Comment by tanweili** [comment]
#151 issue is regarding the main feature added in this branch

**Review by shxr3f — APPROVED** [review]
Seems fine to me can merge!

**Pull request merged**
